const userActionTypes = {
	GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
	EP_SIGNIN_START: "EP_SIGNIN_START",
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_FAILURE: "SIGNIN_FAILURE",
	CHECK_USER_SESSION: "CHECK_USER_SESSION",
	SIGNOUT_START: "SIGNOUT_START",
	SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
	SIGNOUT_FAILURE: "SIGNOUT_FAILURE",
};

export default userActionTypes;
