const userActionTypes = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
	GOOGLE_SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
	GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
	EP_SIGNIN_START: "EP_SIGNIN_START",
	EP_SIGNIN_SUCCESS: "EP_SIGNIN_SUCCESS",
	EP_SIGNIN_FAILURE: "EP_SIGNIN_FAILURE",
};

export default userActionTypes;
